package com.mareike.solrsearch.UI;

import com.mareike.solrsearch.SolrInstance;

import javax.swing.*;

public class FilterFrame extends javax.swing.JFrame {

    private javax.swing.DefaultComboBoxModel<String> creatorComboBoxModel;
    private javax.swing.DefaultComboBoxModel<String> dateComboBoxModel;
    private javax.swing.DefaultComboBoxModel<String> formatComboBoxModel;
    /**
     * Creates new form NewJFrame
     */
    public FilterFrame(SolrInstance solr) {
        setBoxModels(solr);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        ButtonGroup buttonGroupSort = new javax.swing.ButtonGroup();
        Box.Filler filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        JPanel preferencePanel = new javax.swing.JPanel();
        Box.Filler filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        JLabel preferencesLabel = new javax.swing.JLabel();
        JPanel preferencesContentPane = new javax.swing.JPanel();
        JPanel creatorPreferencesPanel = new javax.swing.JPanel();
        JCheckBox creatorPreferencesCheckBox = new javax.swing.JCheckBox();
        JComboBox creatorPreferencesComboBox = new javax.swing.JComboBox<>();
        JPanel datePreferencesPanel = new javax.swing.JPanel();
        JCheckBox datePreferencesCheckBox = new javax.swing.JCheckBox();
        JComboBox datePreferencesComboBox = new javax.swing.JComboBox<>();
        JPanel formatPreferencesPanel = new javax.swing.JPanel();
        JCheckBox formatPreferencesCheckBox = new javax.swing.JCheckBox();
        JComboBox formatPreferencesComboBox = new javax.swing.JComboBox<>();
        JSeparator jSeparator1 = new javax.swing.JSeparator();
        Box.Filler filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        JPanel filterPanel = new javax.swing.JPanel();
        Box.Filler filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        JLabel filterLabel = new javax.swing.JLabel();
        JPanel filterContentPane = new javax.swing.JPanel();
        JPanel creatorFilterPanel = new javax.swing.JPanel();
        JCheckBox creatorFilterCheckBox = new javax.swing.JCheckBox();
        JComboBox creatorFilterComboBox = new javax.swing.JComboBox<>();
        JPanel dateFilterPanel = new javax.swing.JPanel();
        JCheckBox dateFilterCheckBox = new javax.swing.JCheckBox();
        JComboBox dateFilterComboBox = new javax.swing.JComboBox<>();
        JPanel fileFilterPanel = new javax.swing.JPanel();
        JCheckBox formatFilterCheckBox = new javax.swing.JCheckBox();
        JComboBox formatFilterComboBox = new javax.swing.JComboBox<>();
        JSeparator jSeparator2 = new javax.swing.JSeparator();
        JPanel sortPanel = new javax.swing.JPanel();
        Box.Filler filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        JLabel sortLabel = new javax.swing.JLabel();
        Box.Filler filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        JPanel filterContentPane1 = new javax.swing.JPanel();
        Box.Filler filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0));
        JRadioButton relevanceRadioButton = new javax.swing.JRadioButton();
        JRadioButton creationDateRadioButton = new javax.swing.JRadioButton();
        JPanel footer = new javax.swing.JPanel();
        JButton finishButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        filler2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(filler2);

        preferencePanel.setBackground(new java.awt.Color(255, 255, 255));
        preferencePanel.setMinimumSize(new java.awt.Dimension(104, 100));
        preferencePanel.setPreferredSize(new java.awt.Dimension(1296, 100));
        preferencePanel.setLayout(new javax.swing.BoxLayout(preferencePanel, javax.swing.BoxLayout.LINE_AXIS));
        preferencePanel.add(filler4);

        preferencesLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        preferencesLabel.setText("preferences");
        preferencesLabel.setMaximumSize(new java.awt.Dimension(104, 249));
        preferencesLabel.setPreferredSize(new java.awt.Dimension(150, 249));
        preferencePanel.add(preferencesLabel);

        preferencesContentPane.setBackground(new java.awt.Color(255, 255, 255));
        preferencesContentPane.setPreferredSize(new java.awt.Dimension(500, 200));
        preferencesContentPane.setLayout(new java.awt.GridLayout(4, 1));

        creatorPreferencesPanel.setBackground(new java.awt.Color(255, 255, 255));
        creatorPreferencesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        creatorPreferencesCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        creatorPreferencesCheckBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        creatorPreferencesCheckBox.setText("created by");
        creatorPreferencesCheckBox.setPreferredSize(new java.awt.Dimension(180, 33));
        creatorPreferencesPanel.add(creatorPreferencesCheckBox);

        creatorPreferencesComboBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        creatorPreferencesComboBox.setModel(creatorComboBoxModel);
        creatorPreferencesPanel.add(creatorPreferencesComboBox);

        preferencesContentPane.add(creatorPreferencesPanel);

        datePreferencesPanel.setBackground(new java.awt.Color(255, 255, 255));
        datePreferencesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        datePreferencesCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        datePreferencesCheckBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        datePreferencesCheckBox.setText("creation date");
        datePreferencesCheckBox.setPreferredSize(new java.awt.Dimension(180, 33));
        datePreferencesPanel.add(datePreferencesCheckBox);

        datePreferencesComboBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        datePreferencesComboBox.setModel(dateComboBoxModel);
        datePreferencesPanel.add(datePreferencesComboBox);

        preferencesContentPane.add(datePreferencesPanel);

        formatPreferencesPanel.setBackground(new java.awt.Color(255, 255, 255));
        formatPreferencesPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        formatPreferencesCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        formatPreferencesCheckBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        formatPreferencesCheckBox.setText("file format");
        formatPreferencesCheckBox.setPreferredSize(new java.awt.Dimension(180, 33));
        formatPreferencesPanel.add(formatPreferencesCheckBox);

        formatPreferencesComboBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        formatPreferencesComboBox.setModel(formatComboBoxModel);
        formatPreferencesPanel.add(formatPreferencesComboBox);

        preferencesContentPane.add(formatPreferencesPanel);

        preferencePanel.add(preferencesContentPane);

        getContentPane().add(preferencePanel);

        jSeparator1.setMaximumSize(new java.awt.Dimension(32767, 10));
        getContentPane().add(jSeparator1);

        filler1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(filler1);

        filterPanel.setBackground(new java.awt.Color(255, 255, 255));
        filterPanel.setMinimumSize(new java.awt.Dimension(68, 100));
        filterPanel.setPreferredSize(new java.awt.Dimension(742, 100));
        filterPanel.setLayout(new javax.swing.BoxLayout(filterPanel, javax.swing.BoxLayout.LINE_AXIS));
        filterPanel.add(filler3);

        filterLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        filterLabel.setText("filter by");
        filterLabel.setToolTipText("");
        filterLabel.setPreferredSize(new java.awt.Dimension(150, 249));
        filterPanel.add(filterLabel);

        filterContentPane.setBackground(new java.awt.Color(255, 255, 255));
        filterContentPane.setPreferredSize(new java.awt.Dimension(500, 200));
        filterContentPane.setLayout(new java.awt.GridLayout(4, 1));

        creatorFilterPanel.setBackground(new java.awt.Color(255, 255, 255));
        creatorFilterPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        creatorFilterCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        creatorFilterCheckBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        creatorFilterCheckBox.setText("creator");
        creatorFilterCheckBox.setPreferredSize(new java.awt.Dimension(180, 33));
        creatorFilterPanel.add(creatorFilterCheckBox);

        creatorFilterComboBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        creatorFilterComboBox.setModel(creatorComboBoxModel);
        creatorFilterPanel.add(creatorFilterComboBox);

        filterContentPane.add(creatorFilterPanel);

        dateFilterPanel.setBackground(new java.awt.Color(255, 255, 255));
        dateFilterPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        dateFilterCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        dateFilterCheckBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        dateFilterCheckBox.setText("creation date");
        dateFilterCheckBox.setPreferredSize(new java.awt.Dimension(180, 33));
        dateFilterPanel.add(dateFilterCheckBox);

        dateFilterComboBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        dateFilterComboBox.setModel(dateComboBoxModel);
        dateFilterPanel.add(dateFilterComboBox);

        filterContentPane.add(dateFilterPanel);

        fileFilterPanel.setBackground(new java.awt.Color(255, 255, 255));
        fileFilterPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 30, 5));

        formatFilterCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        formatFilterCheckBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        formatFilterCheckBox.setText("file format");
        formatFilterCheckBox.setPreferredSize(new java.awt.Dimension(180, 33));
        fileFilterPanel.add(formatFilterCheckBox);

        formatFilterComboBox.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        formatFilterComboBox.setModel(formatComboBoxModel);
        fileFilterPanel.add(formatFilterComboBox);

        filterContentPane.add(fileFilterPanel);

        filterPanel.add(filterContentPane);

        getContentPane().add(filterPanel);

        jSeparator2.setMaximumSize(new java.awt.Dimension(32767, 5));
        getContentPane().add(jSeparator2);

        sortPanel.setBackground(new java.awt.Color(255, 255, 255));
        sortPanel.setMinimumSize(new java.awt.Dimension(0, 50));
        sortPanel.setPreferredSize(new java.awt.Dimension(547, 50));
        sortPanel.setLayout(new javax.swing.BoxLayout(sortPanel, javax.swing.BoxLayout.LINE_AXIS));
        sortPanel.add(filler5);

        sortLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        sortLabel.setText("sort by");
        sortLabel.setMaximumSize(new java.awt.Dimension(150, 249));
        sortLabel.setPreferredSize(new java.awt.Dimension(150, 249));
        sortLabel.setVerifyInputWhenFocusTarget(false);
        sortLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        sortPanel.add(sortLabel);
        sortPanel.add(filler7);

        filterContentPane1.setBackground(new java.awt.Color(255, 255, 255));
        filterContentPane1.setPreferredSize(new java.awt.Dimension(500, 200));
        filterContentPane1.setLayout(new java.awt.GridLayout(4, 1));
        filterContentPane1.add(filler6);

        relevanceRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        relevanceRadioButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        relevanceRadioButton.setText("relevance");
        buttonGroupSort.add(relevanceRadioButton);
        filterContentPane1.add(relevanceRadioButton);

        creationDateRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        creationDateRadioButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        creationDateRadioButton.setText("creation date");
        buttonGroupSort.add(creationDateRadioButton);
        filterContentPane1.add(creationDateRadioButton);

        sortPanel.add(filterContentPane1);

        getContentPane().add(sortPanel);

        footer.setBackground(new java.awt.Color(255, 255, 255));
        footer.setMaximumSize(new java.awt.Dimension(32767, 50));
        footer.setPreferredSize(new java.awt.Dimension(821, 50));
        footer.setLayout(new java.awt.GridBagLayout());

        finishButton.setText("Done");
        footer.add(finishButton, new java.awt.GridBagConstraints());

        getContentPane().add(footer);

        pack();
    }// </editor-fold>

    private void setBoxModels(SolrInstance solr){
        formatComboBoxModel = new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" });
        dateComboBoxModel = new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" });
        creatorComboBoxModel = new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" });
    }
}
